# Generated by Django 2.2 on 2022-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='password',
            field=models.CharField(help_text='密码', max_length=20, null=True, verbose_name='密码'),
        ),
    ]
