# Generated by Django 2.2 on 2022-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_personinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='staff_id',
            field=models.IntegerField(help_text='员工编号', max_length=5, null=True, unique=True, verbose_name='员工编号'),
        ),
    ]
