# Generated by Django 2.2 on 2022-07-09 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0008_auto_20220709_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('regional_manager', models.CharField(max_length=20, verbose_name='区域经理')),
                ('business_people', models.CharField(max_length=20, verbose_name='业务人员')),
                ('volume', models.IntegerField(verbose_name='成交数量')),
                ('turnover', models.FloatField(verbose_name='成交金额')),
                ('input_number', models.IntegerField(verbose_name='建档数量')),
            ],
            options={
                'verbose_name': '行政区域',
                'verbose_name_plural': '行政区域',
                'ordering': ('volume',),
            },
        ),
        migrations.CreateModel(
            name='HouseMainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='户主姓名')),
                ('id_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='身份证号码')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], help_text='性别', verbose_name='性别')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('is_local', models.BooleanField(help_text='是否常驻', verbose_name='是否常驻')),
                ('political_landscape', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('staff', models.CharField(max_length=20, verbose_name='个人职业')),
                ('health', models.IntegerField(choices=[(0, '良好'), (1, '较差')], help_text='健康状况', verbose_name='健康状况')),
                ('marriage', models.IntegerField(choices=[(0, '已婚'), (1, '未婚')], help_text='婚姻状况', verbose_name='婚姻状况')),
                ('culture', models.CharField(max_length=20, verbose_name='文化程度')),
                ('area', models.CharField(max_length=20, verbose_name='所属区域')),
                ('house_num', models.IntegerField(default=0, verbose_name='农房数量')),
                ('house_area', models.FloatField(default=0, verbose_name='农房面积(平方米)')),
                ('house_value', models.FloatField(default=0, verbose_name='农房价值')),
                ('car_num', models.IntegerField(default=0, verbose_name='汽车数量')),
                ('mech_num', models.IntegerField(default=0, verbose_name='农业机械数量')),
                ('mech_value', models.FloatField(default=0, verbose_name='农用机械价值(元)')),
                ('mech_photo', models.ImageField(null=True, upload_to='', verbose_name='农用机械图片')),
                ('labor_num', models.IntegerField(default=1, verbose_name='劳动人口')),
                ('provide_num', models.IntegerField(default=1, verbose_name='供养人数')),
                ('family_input', models.FloatField(default=0, verbose_name='家庭收入(元)')),
                ('family_spending', models.FloatField(default=0, verbose_name='家庭支出(元)')),
                ('enterprise_name', models.CharField(max_length=200, null=True, verbose_name='企业名称')),
                ('produce_cycle', models.IntegerField(default=0, null=True, verbose_name='生产经营周期(年)')),
                ('winning_y', models.CharField(max_length=20, null=True, verbose_name='养殖获奖')),
                ('winning_p', models.ImageField(null=True, upload_to='', verbose_name='获奖图片')),
                ('agricultural_subsidies', models.FloatField(default=0, verbose_name='农业补贴')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
                ('loanable', models.FloatField(default=0, verbose_name='贷款金额(元)')),
            ],
            options={
                'verbose_name': '户主建档信息',
                'verbose_name_plural': '户主建档信息',
                'ordering': ('join_time',),
            },
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=20, verbose_name='姓名')),
                ('id_num', models.CharField(help_text='身份证号码', max_length=20, unique=True, verbose_name='身份证号码')),
                ('staff_id', models.IntegerField(help_text='员工编号', max_length=5, null=True, unique=True, verbose_name='员工编号')),
                ('age', models.IntegerField(help_text='年龄', verbose_name='年龄')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], help_text='性别', verbose_name='性别')),
                ('height', models.IntegerField(help_text='身高', null=True, verbose_name='身高(cm)')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱地址')),
                ('weight', models.IntegerField(help_text='体重', null=True, verbose_name='体重(kg)')),
                ('password', models.CharField(help_text='密码', max_length=20, null=True, verbose_name='密码')),
                ('edu_back', models.CharField(help_text='教育背景', max_length=50, verbose_name='教育背景')),
                ('administrator', models.BooleanField(help_text='是否为管理员', verbose_name='是否为管理员')),
                ('boss', models.CharField(help_text='上司', max_length=20, verbose_name='上司')),
                ('Hob_Tal', models.CharField(help_text='特长与喜好', max_length=200, null=True, verbose_name='特长与喜好')),
                ('photo', models.ImageField(help_text='照片', null=True, upload_to='', verbose_name='照片')),
                ('phone_number', models.CharField(help_text='联系电话', max_length=11, verbose_name='联系电话')),
                ('area', models.CharField(help_text='所属区域', max_length=20, verbose_name='所属区域')),
                ('home_address', models.CharField(help_text='家庭住址', max_length=200, null=True, verbose_name='家庭住址')),
                ('join_time', models.DateTimeField(auto_now_add=True, help_text='加入时间', null=True, verbose_name='加入时间')),
                ('person_file', models.TextField(help_text='个人简介', verbose_name='个人简介')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '人员信息',
                'verbose_name_plural': '人员信息',
                'ordering': ('join_time',),
            },
        ),
        migrations.CreateModel(
            name='PerformanceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_id', models.CharField(max_length=32, unique=True, verbose_name='职工编号')),
                ('recept_staff', models.CharField(max_length=32, verbose_name='接收人员')),
                ('pub_staff', models.CharField(max_length=32, verbose_name='发布人')),
                ('pub_time', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('completion_time', models.DateField(null=True, verbose_name='规定完成时间')),
                ('volume', models.IntegerField(verbose_name='成交数量')),
                ('turnover', models.IntegerField(null=True, verbose_name='成交金额')),
                ('task_description', models.TextField(null=True, verbose_name='任务描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.PersonInfo', to_field='id_num')),
            ],
            options={
                'verbose_name': '绩效任务',
                'verbose_name_plural': '绩效任务',
                'ordering': ('pub_time',),
            },
        ),
        migrations.CreateModel(
            name='PeopleOfMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('relation_name', models.CharField(max_length=20, verbose_name='户主姓名')),
                ('relation', models.CharField(max_length=20, null=True, verbose_name='与户主关系')),
                ('id_num', models.CharField(max_length=18, unique=True, verbose_name='身份证号码')),
                ('phone_number', models.CharField(max_length=11, verbose_name='电话号码')),
                ('area', models.CharField(max_length=50, verbose_name='区域')),
                ('user', models.OneToOneField(help_text='关联户主', on_delete=django.db.models.deletion.CASCADE, to='role.HouseMainInfo', to_field='id_number')),
            ],
            options={
                'verbose_name': '户主家庭成员',
                'verbose_name_plural': '户主家庭成员',
            },
        ),
        migrations.AddField(
            model_name='housemaininfo',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.PersonInfo', verbose_name='责任人（接收的业务人员）'),
        ),
    ]
