# Generated by Django 2.2 on 2022-07-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0026_auto_20220710_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
