# Generated by Django 2.2 on 2022-07-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0027_delete_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('regional_manager', models.CharField(max_length=20, verbose_name='区域经理')),
                ('business_people', models.CharField(max_length=20, verbose_name='业务人员')),
                ('volume', models.IntegerField(verbose_name='成交数量')),
                ('turnover', models.FloatField(verbose_name='成交金额')),
                ('input_number', models.IntegerField(verbose_name='建档数量')),
            ],
            options={
                'verbose_name': '行政区域',
                'verbose_name_plural': '行政区域',
                'ordering': ('volume',),
            },
        ),
    ]
