# Generated by Django 2.2 on 2022-07-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0028_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='sex',
            field=models.IntegerField(help_text='性别', verbose_name='性别'),
        ),
    ]
